### ISSUE TITLE
노래 재생안돼요

### ISSUE THREAD

**Issue by LUDIN1** [Emin-G/StellarLoom#1]
봇이 실행은 잘되고 오류는 없는데 재생하면 노래를 안트네요

**Comment by Emin-G** [comment]
해당 부분은 Lavalink 설정 문제로 보입니다!

혹시 버전 탭에서 v.2.3.0 버전을 다운로드 하여 사용하셨다면
해당 문제가 발생할 수 있습니다.

v.2.3.1 버전 또는 master 브랜치 자체를 다운로드하여 이용하시면 정상적으로
작동할 것으로 보입니다.

감사합니다!
