### ISSUE TITLE
아직도 안됩니다 ㅠㅠ

### ISSUE THREAD

**Issue by LUDIN1** [Emin-G/StellarLoom#2]
2.3.1v 으로 하고 lavalink 3.7.12 짜리를 깔았는데 똑같이 노래를 안틉니다 ㅠㅠ

**Comment by Emin-G** [comment]
올바르게 설정하였을 때 정상 작동하는 것을 확인하였습니다!
설정을 잘못하셨을 가능성이 매우 높습니다.

Lavalink 로그 및 코드 실행 시 표시되는 에러 로그를 첨부해주셔야 도움을 드릴 수 있습니다.
